#language: java
#
#jdk:
#  - oraclejdk8
#
#cache:
#  directories:
#    - '$HOME/.m2/repository'
#
#script:
#  - mvn clean package -DskipTests=true
#
#after_success:
#  - cd ./target
#  - git init
#  - git config user.name "YuePeng"
#  - git config user.email "erupt@126.com"
#  - git add spring-boot-jsp.war
#  - git commit -m "version 1"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
#
#branches:
#  only:
#    - Master
#
#notifications:
#  email: false
#
#env:
#  global:
#    - GH_REF=github.com/erupts/erupt.git