erupt:
  csrfInspect: false
  job.enable: true
  upload-path: /Users/liyuepeng/Pictures/temp
  auth:
    expireTimeByLogin: 60
    recordOperateLog: true
  dbs:
    - datasource:
        name: mysql
        url: jdbc:mysql://39.104.174.237:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root2
        password: B5xC&YccqyV
      jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
#  attachmentProxy: xyz.erupt.example.handler.QiniuOosProxy
openApi:
  #是否热读取xml配置，生产环境不要开启此功能
  hotReadXml: true

spring:
  datasource:
    hikari:
      max-lifetime: 30000
    url: jdbc:mysql://39.104.174.237:3306/erupt?useUnicode=true&characterEncoding=UTF-8
    username: erupt
    password: leLPvYbQQ!27st2FuxtO
  #      url: jdbc:h2:file:./demo/src/main/resources/erupt_db
  #      platform: h2
  #      username: erupt
  #      password: erupt_h2
  #      driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
  #      ddl-auto: update
  mail:
    username: lixin@wingstimes.com
    password: Lx2159200
    host: smtp.exmail.qq.com
    port: 465
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
    data:
      mongodb:
        uri: mongodb://erupt:erupt@localhost/erupt
  h2:
    console:
      enabled: false
      path: /h2_console
  redis:
    database: 0
    timeout: 10000
    host: 127.0.0.1
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    cache.period: 2592000
    chain.cache: true
  profiles:
    active: @environment@
server:
  port: 9999
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
#  servlet:
#    context-path: /demo
