erupt:
  scanner-package:
    - xyz.erupt
    - com.xxxxx
  allow-request-file-type: pdf
erupt-auth:
  expireTimeByLogin: 60
openApi:
  #是否热读取xml配置，生产环境不要开启此功能
  hotReadXml: true
spring:
  datasource:
    hikari:
      max-lifetime: 30000
    url: jdbc:mysql://39.104.174.237:3306/erupt?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: E3&$cBW#
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    timeout: 10000
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    cache.period: 2592000
    chain.cache: true
  profiles:
    active: @environment@
server:
  port: 9999
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
