erupt:
  scanner-package:
    - xyz.erupt
    - com.xxxxx
  allow-request-file-type: pdf
  upload-path: /Users/liyuepeng/Pictures/temp
  hot-build: true
  redis-session: true
  dataSources: one
erupt-auth:
  expireTimeByLogin: 60
openApi:
  #是否热读取xml配置，生产环境不要开启此功能
  hotReadXml: true
spring:
  datasource:
    url: jdbc:mysql://39.104.174.237:3306/erupt?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: E3&$cBW#
    one:
      url: jdbc:sqlserver://59.110.40.167:3434;DatabaseName=erupt
      username: sa
      password: msSQL2017
      database-platform: org.hibernate.dialect.SQLServer2008Dialect
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    timeout: 10000
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    cache.period: 2592000
    chain.cache: true
server:
  port: 9999
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
