#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erupt2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: 19824135
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000
    database: 0
server:
  port: 9999