#jdbc
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/erupt?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: root
      password: plkjplkj
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update